version: '3.7'

services:
  alesap:
    image: davidsiaw/alesap-server
    deploy:
      update_config:
        order: stop-first
    environment:
      LETSENCRYPT_HOST: api.alesap.astrobunny.net
      VIRTUAL_HOST: api.alesap.astrobunny.net
      VIRTUAL_PORT: 3000
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${ALESAP_MASTER_KEY}
      ALLOWED_ORIGINS: alesap.astrobunny.net,alesap.blankaex.reisen
      DATABASE_URL: ${ALESAP_DB_URL}
      THING: 1
    container_name: alesap
    networks:
      - alesap

  alesap-db:
    image: postgres:17
    deploy:
      update_config:
        order: stop-first
    environment:
      POSTGRES_PASSWORD: ${ALESAP_PG_PASS}
      POSTGRES_USER: ${ALESAP_PG_USER}
      POSTGRES_DB: ${ALESAP_PG_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: alesap-db
    volumes:
      - alesap-data:/var/lib/postgresql/data
      - postgres-config:/etc/postgresql
    networks:
      - alesap
    ports:
      - 5432
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf';
volumes:
  alesap-data:
    external: true
  postgres-config:
    external: true

networks:
  alesap:
    external: true
